routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\HomeController;
use App\Http\Controllers\PageController as FrontPage;
use App\Http\Controllers\Admin\AdminController;
use App\Http\Controllers\Admin\PageController as AdminPage;
use App\Http\Controllers\Admin\AuthController as AdminAuth;
use App\Http\Controllers\Admin\BannerController;
use App\Http\Controllers\Admin\UserController as AdminUser;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', [HomeController::class, 'home']);
Route::get('/page/{identifier?}', [FrontPage::class, 'page']);





Route::get('/admin/login', [AdminAuth::class, 'login'])->name('login');
Route::get('/admin/logout', [AdminAuth::class, 'logout']);
Route::post('/admin/auth/authenticate', [AdminAuth::class, 'authenticate']);

Route::middleware(['auth'])->group(function(){
    Route::get('/admin', [AdminController::class, 'dashboard']);
    Route::get('/admin/sites', [AdminController::class, 'sites']);
    Route::post('/admin/getSites', [AdminController::class, 'getSites']);
    Route::get('/admin/manageSite/{id?}', [AdminController::class, 'manageSite']);
    Route::post('/admin/site/save', [AdminController::class, 'saveSite']);
    Route::get('/admin/header', [AdminController::class, 'header']);
    Route::get('/admin/footer', [AdminController::class, 'footer']);

    Route::get('/admin/page/{identifier?}/{site_id?}', [AdminPage::class, 'page']);
    Route::post('/admin/page/save', [AdminPage::class, 'savePage']);

    Route::get('/admin/banners', [BannerController::class, 'banners']);
    Route::post('/admin/banners/save', [BannerController::class, 'saveSiteBanner']);
    Route::get('/admin/banners/manageBanner/{site_id?}/{id?}', [BannerController::class, 'manageBanner']);
    Route::post('/admin/banners/getBanners', [BannerController::class, 'getBanners']);
    Route::post('/admin/banner/delete', [BannerController::class, 'deleteBanner']);

    Route::get('/admin/users', [AdminUser::class, 'users']);
    Route::post('/admin/user/getUsers', [AdminUser::class, 'getUsers']);
    Route::get('/admin/user/manageUser/{id?}', [AdminUser::class, 'manageUser']);
    Route::post('/admin/user/save', [AdminUser::class, 'saveUser']);


});

app/Models/User.php
<?php

namespace App\Models;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;
use Laravel\Sanctum\HasApiTokens;
use Illuminate\Support\Facades\Hash;
class User extends Authenticatable
{
    use HasApiTokens, HasFactory, Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array<int, string>
     */
    protected $fillable = [
        'name',
        'email',
        'password',
        'role_key'
    ];

    /**
     * The attributes that should be hidden for serialization.
     *
     * @var array<int, string>
     */
    protected $hidden = [
        'password',
        'remember_token',
    ];

    /**
     * The attributes that should be cast.
     *
     * @var array<string, string>
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];

    public function setPasswordAttribute($password)
    {
        $this->attributes['password'] = Hash::make($password);
    }
}

app/Http/Controllers/Admin/UserController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use App\Helpers\Helper;
use App\Models\User;
use App\Models\Role;
use App\Models\Site;
use App\Models\UserSite;
use Exception;

class UserController extends Controller
{
    public function users(Request $request)
    {
        $mySites=Helper::getMySites();
        view()->share('selectedMenuItem', 'users');
        return view('admin.user.users', ['pageTitle' => 'Admin | Users List', 'pageName'=>'Users', 'mySites'=>$mySites]);
    }
    public function getUsers(Request $request)
    {
        $site_id=$request->site_id;
        $offset=$request->start;
        $limit=$request->length;
        $searchText=$request->search['value']   ;
        $sortOrderColumnIndex=$request->order[0]['column'];
        $sortOrder=$request->order[0]['dir'];
        $columns=$request->columns;
        $filter=array();

        $query=User::select('users.*')->offset($offset)
                        ->limit($limit)
                        ->join('user_sites', function($join ) use ($site_id){
                            $join->on('users.id', '=', 'user_sites.user_id')
                            ->where('user_sites.site_id', $site_id);
                        });
                        //->join('user_sites','users.id', '=', 'user_sites.user_id')
                        //->where('user_sites.site_id', $site_id);


        foreach($columns as $_column){
            if($_column['data']==$sortOrderColumnIndex){
               //$sortColumnName=$_column['name'];
                $query->orderBy("users.".$_column['name'], $sortOrder);
            }
            if($searchText!="" && $_column['searchable']=="true"){
                $query->orWhere("users.".$_column['name'], 'like', "%".$searchText."%");
            }
        }
        //dd($query->toSql());
        $result=$query->get();

        $finalArray['data']=array();
        foreach($result as $row){
            $finalArray['data'][]=array(
                $row['id'],
                $row['name'],
                $row['email'],
                $row['role_key'],
                "<a class='btn btn-info btn-sm' href='".url('/admin/user/manageUser/'.$row['id'])."'>Edit</a>"
            );
        }
        $finalArray['draw']=$request->draw;
        $finalArray['recordsTotal']=User::join('user_sites', function($join ) use ($site_id){
                                                $join->on('users.id', '=', 'user_sites.user_id')
                                                ->where('user_sites.site_id', $site_id);
                                        }) 
                                        ->count();
        $finalArray['recordsFiltered']=User::orWhere($filter)
                                        ->join('user_sites', function($join ) use ($site_id){
                                            $join->on('users.id', '=', 'user_sites.user_id')
                                            ->where('user_sites.site_id', $site_id);
                                        })  
                                        ->count();

        return response(json_encode($finalArray), 200)
                  ->header('Content-Type', 'application/json');
    }
    public function manageUser($user_id=null)
    {
        $pageLabel="Add New User";
        $userSites=array();
        $user=null;
        if(!is_null($user_id)){
            $pageLabel="Edit User";
            $user=User::where('id', $user_id)->first();
            if(is_null($user)){
                echo "Invalid user id.";
                return false;
            }
            $userSites=UserSite::where('user_id', $user_id)->get();
        }
        view()->share('selectedMenuItem', 'users');
        $roles=Role::where('role_key','<>', 'super_admin')->get();
        $sites=Site::get();
        
        return view('admin.user.manage-user', ['userSites'=>$userSites,'sites'=>$sites, 'roles'=>$roles, 'pageLabel'=>$pageLabel, 'pageTitle' => 'Admin | Manage User', 'user'=>$user]);
    }

    public function saveUser(Request $request)
    {
        $user=User::where(['id'=>$request->user_id])->first();
         
        
        if(is_null($user)){
            $data=[
                'name'=>$request->name,
                'role_key'=>$request->role_key,
                'email'=>$request->email,
                'password'=>$request->password,
                'created_at' => date('Y-m-d H:i:s')
            ];
            try{
                $user=User::create($data);
            }catch(Exception $e){

        return response()->json(array("status"=>"error", "message"=> $e->getMessage()) );
            }
            
        }else{
            $user->updated_at=date('Y-m-d H:i:s');
            $user->name=$request->name;
            if(!is_null($request->password) && $request->password !=""){
                $user->password=$request->password;
            }
            $user->role_key=$request->role_key;
            $user->save();
        }

        if(!is_null($request->site)){
            UserSite::where(['user_id'=>$user->id])->delete();
            $arrSite=explode(',', $request->site);
            foreach($arrSite as $site_id){
                UserSite::create(['user_id'=>$user->id, 'site_id'=>$site_id]);
            }
        }
       
        return response()->json(array("status"=>"success", "message"=> 'User information saved succesfully against user id '. $user->id, 'user_id'=>$user->id) );
    }

}

app/View/Components/AdminLayout.php
<?php

namespace App\View\Components;

use Illuminate\View\Component;

class AdminLayout extends Component
{
    /**
     * Create a new component instance.
     *
     * @return void
     */
    public function __construct()
    {
        //
    }

    /**
     * Get the view / contents that represent the component.
     *
     * @return \Illuminate\Contracts\View\View|\Closure|string
     */
    public function render()
    {
        return view('layouts.admin');
    }
}

resources/views/admin/user/manage-user.blade.php
<x-admin-layout>

    @section('title', $pageTitle)
    @section('customScript')
        <script src="{{ asset('admin_assets/plugins/jquery-validation/jquery.validate.js') }}"></script>
        <script src="{{ asset('admin_assets/plugins/jquery-validation/additional-methods.js') }}"></script>
        <script src="{{ asset('admin_assets/dist/js/users.js?v=11') }}"></script>
    @endsection
    @section('customHead')
        <meta name="csrf_token" content="{{ csrf_token() }}" />
    @endsection

    <!-- Content Header (Page header) -->
    <div class="content-header">
        <div class="container-fluid">

            

          <div class="row mb-2">
            <div class="col-sm-6">
                <a href="{{url("/admin/users")}}" class="btn btn-primary">Back to Users</a>
                 

                {{-- <select class="custom-select" id="comboSiteIdManageBanner" name="comboSiteIdManageBanner">
                    @foreach ($mySites as $_mySite)
                        <option value="{{$_mySite->id}}" @if($site->id ==$_mySite->id ) selected="selected" @endif >{{$_mySite->name}} - {{$_mySite->url}}</option>
                    @endforeach
                </select> --}}
            </div><!-- /.col -->
            <div class="col-sm-6">
              <ol class="breadcrumb float-sm-right">
                <li class="breadcrumb-item"><a href="#">Home</a></li>
                <li class="breadcrumb-item active">{{$pageLabel}}</li>
              </ol>
            </div><!-- /.col -->
          </div><!-- /.row -->
        </div><!-- /.container-fluid -->
      </div>
      <!-- /.content-header -->
    <!-- Main content -->
      <section class="content">
        <div class="container-fluid">
            <div class="row">
                <!-- left column -->
                <div class="col-md-12">
                    <!-- general form elements -->
                    <div class="card card-primary">
                        <div class="card-header">
                            <h3 class="card-title">{{$pageLabel}}</h3>
                        </div>
                        <!-- /.card-header -->
                        <!-- form start -->
                        <form id="frmUser" method="POST" action="{{url("/admin/user/save")}}" enctype="multipart/form-data">
                            @csrf
                            <div class="card-body">
                                <div class="form-group">
                                    <label for="name">Full Name</label>
                                    <input type="text" class="form-control" id="name" name="name" value="{{isset($user->name) ? $user->name : ""}}">
                                    <input type="hidden" class="form-control" id="user_id" name="user_id" value="{{isset($user->id) ? $user->id : ""}}">
                                </div>
                                <div class="form-group">
                                    <label for="email">Email</label>
                                    <input type="email" class="form-control" id="email" name="email" @if (isset($user->email))
                                        readonly
                                    @endif value="{{isset($user->email) ? $user->email : ""}}">
                                </div>
                                <div class="form-group">
                                    <label for="name">Password</label>
                                    <input type="text" class="form-control" id="password" name="password" value="">
                                </div>
                                <div class="form-group">
                                    <label for="role_key">Role</label>
                                    <select class="custom-select" id="role_key" name="role_key">
                                        @foreach ($roles as $_role)
                                             
                                            <option value="{{$_role->role_key}}" @if(isset($user->role_key) && $_role->role_key == $user->role_key ) selected="selected" @endif    > {{$_role->description}} </option>

                                        @endforeach
                                    </select>
                                </div>
                                <div class="form-group">
                                    <label for="email">Sites</label>
                                    <select multiple class="custom-select" id="site" name="site[]">
                                        @foreach ($sites as $_site)
                                            <option value="{{$_site->id}}" 
                                                @foreach ($userSites as $_userSites )
                                                    @if($_userSites->site_id == $_site->id ) selected="selected" @endif  
                                                @endforeach
                                                
                                                
                                                >{{$_site->name}} - {{$_site->url}} </option>
                                        @endforeach
                                    </select>
                                </div>


                            </div>
                            <!-- /.card-body -->

                            <div class="card-footer">
                                <button type="submit" id="cmdSavePage" class="btn btn-primary">Submit</button>
                            </div>

                        </form>
                    </div>
                    <!-- /.card -->

                </div>
            </div><!-- /.row -->

            <div class="row">
                <div class="col-md-12">
                    <div id="divMessage" style="display:none;"></div>
                </div>
            </div>
        </div><!-- /.container-fluid -->
      </section>
      <!-- /.content -->
    </x-admin-layout>

resources/views/admin/user/users.blade.php
<x-admin-layout>

    @section('title', $pageTitle)
    @section('customScript')
        <script src="{{ asset('admin_assets/dist/js/users.js') }}"></script>
    @endsection

    @section('customHead')
    <meta name="csrf_token" content="{{ csrf_token() }}" />
    @endsection
    <!-- Content Header (Page header) -->
    <div class="content-header">
        <div class="container-fluid">
            <div class="row mb-1">
                <div class="col-sm-3">
                     <a  class="btn btn-primary"  href="{{url('admin/user/manageUser')}}"><i class="fas fa-plus"></i> Add New User</a >
                </div>
                <div class="col-sm-6">
                    <select class="custom-select" id="comboSiteId" name="comboSiteId">
                        @foreach ($mySites as $_mySite)
                            <option value="{{$_mySite->id}}"   >{{$_mySite->name}} - {{$_mySite->url}}</option>
                        @endforeach
                    </select>
                </div>
                <!-- /.col -->
                <div class="col-sm-3">
                    <ol class="breadcrumb float-sm-right">
                        <li class="breadcrumb-item"><a href="{{url("/admin")}}">Dashboard</a></li>
                        <li class="breadcrumb-item active">{{$pageName}}</li>
                    </ol>
                </div><!-- /.col -->
            </div><!-- /.row -->
        </div><!-- /.container-fluid -->
    </div>
    <!-- /.content-header -->
    <!-- Main content -->
    <section class="content">
        <div class="container-fluid">
            <!-- Small boxes (Stat box) -->

            <!-- /.row -->

            <!-- Main row -->

            <div class="row">
                <div class="col-12">

                    <div class="card card-primary">
                        <div class="card-header">
                            <h3 class="card-title">{{$pageName}} Listing</h3>
                        </div>
                        <!-- /.card-header -->
                        <div class="card-body">
                            <table id="tblUsers" class="table table-bordered table-striped">
                                <thead>
                                    <tr>
                                        <th>User Id</th>
                                        <th>Name</th>
                                        <th>Email</th>
                                        <th>Role</th>
                                        <th></th>
                                    </tr>
                                </thead>

                            </table>
                        </div>
                        <!-- /.card-body -->
                    </div>
                    <!-- /.card -->

                </div>
            </div>
            <!-- /.row (main row) -->
        </div><!-- /.container-fluid -->
    </section>
    <!-- /.content -->
</x-admin-layout>